name: multidex
channels:
  - conda-forge
dependencies:
  - python=3.11
  - async_timeout
  - choreographer>=0.99.6
  - conda-build
  - cytoolz
  - dash
  - django
  - django-extensions
  - dustgoggles
  - fire
  - flask-caching
  - fs
  - git
  - marslab
  - matplotlib
  - more-itertools
  - pandas>=2.2.0
  - pillow
  - pyarrow
  - pip
  - numpy
  - plotly
  - pytest
  - scikit-learn
