name: multidex
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - conda-build
  - rasterio
  - python-levenshtein
  - gdal
  - fs
  - clize
  - django
  - pillow
  - dash
  - toolz
  - cytoolz
  - jupyter
  - flask-caching
  - django-extensions
  - more-itertools
  - numpy
  - pandas
  - plotly
  - matplotlib
  - werkzeug==1.0.1
  - scikit-learn
  - pvl
  - sympy
  - pip
  - pip:
    - "git+https://github.com/MillionConcepts/pdr.git"
    - "git+https://github.com/MillionConcepts/marslab.git"



# TODO: find some way to deal with the posixemulation deprecation in werkzeug -- PR to flask-caching, vendoring?


