name: multidex
channels:
  - conda-forge
dependencies:
  - python>=3.11
  # Conda dependencies have temporarily been stubbed out while the
  # package is under overhaul.  After creating the conda environment,
  # use `pip install -e .` to install multidex along with all its
  # dependencies.  (This will install the dependencies from PyPI
  # rather than from Conda.)
