[project]
name          = "multidex"
version       = "0.20.0"
description   = "Multidimensional multi/hyperspectral data exploration"
readme        = "README.md"
authors       = [ { name = "Million Concepts" } ]
license       = "BSD-3-Clause"
license-files = ["LICENSE.md"]

classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Environment :: Web Environment",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Astronomy",
]

requires-python = ">=3.11"
dependencies = [
]

[project.urls]
Repository = "https://github.com/MillionConcepts/multidex"

[project.scripts]

[build-system]
requires = ["setuptools >= 77"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = [
    "multidex",
    "multidex.*",
]
# remove after everything in _old is merged back
exclude = [
    "_old",
    "_old.*",
]
namespaces = false
where = ["."]
