name: multidex
channels:
  - conda-forge
dependencies:
  - python=3.10
  - conda-build
  - scikit-learn
  - fs
  - clize
  - django
  - pillow
  - dash
  - toolz
  - cytoolz
  - flask-caching
  - django-extensions
  - more-itertools
  - numpy
  - pandas
  - plotly
  - pytest
  - dustgoggles
  - matplotlib
  - git
  - pip
  - python-kaleido
  - marslab
  - pip:
    - wand
