name: multidex
channels:
  - conda-forge
dependencies:
  - python=3.10
  - conda-build
  - cytoolz
  - dash
  - django
  - django-extensions
  - dustgoggles
  - fire
  - flask-caching
  - fs
  - git
  - marslab
  - matplotlib
  - more-itertools
  - pandas
  - pillow
  - pip
  - numpy
  - plotly
  - pytest
  - scikit-learn
  - pip:
      - kaleido==0.1.0post1
