name: multidex
channels:
  - conda-forge
dependencies:
  - python=3.9
  - conda-build
  - scikit-learn
  - fs
  - clize
  - django
  - pillow
  - dash
  - toolz
  - cytoolz
  - flask-caching
  - django-extensions
  - more-itertools
  - numpy
  - pandas
  - plotly
  - pytest
  - fontconfig=2.13.94
  - itsdangerous=2.0.1
  - markupsafe=2.0.1
  - werkzeug==1.0.1
  - git
  - pip
  - python-kaleido
  - pip:
    - "git+https://github.com/MillionConcepts/dustgoggles.git"
    - "git+https://github.com/MillionConcepts/marslab.git"
    - wand



# TODO: find some way to deal with the posixemulation deprecation in werkzeug -- PR to flask-caching, vendoring?


