# Generated by Django 3.0.6 on 2020-06-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mspec',
            name='L6_mean',
            field=models.FloatField(db_index=True, verbose_name='L6 mean'),
        ),
        migrations.AlterField(
            model_name='mspec',
            name='L6_stdev',
            field=models.FloatField(db_index=True, verbose_name='L6 stdev'),
        ),
        migrations.AlterField(
            model_name='mspec',
            name='R6_mean',
            field=models.FloatField(db_index=True, verbose_name='R6 mean'),
        ),
        migrations.AlterField(
            model_name='mspec',
            name='R6_stdev',
            field=models.FloatField(db_index=True, verbose_name='R6 stdev'),
        ),
    ]
