# Generated by Django 3.1.6 on 2021-02-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mspec',
            name='group',
        ),
        migrations.AlterField(
            model_name='mobs',
            name='seq_id',
            field=models.CharField(db_index=True, max_length=20, verbose_name="sequence id, e.g. 'mcam00001'"),
        ),
    ]
