# Generated by Django 3.0.6 on 2020-06-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0002_auto_20200620_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobs',
            name='target_el',
            field=models.FloatField(db_index=True, null=True, verbose_name='Target Elevation'),
        ),
        migrations.AlterField(
            model_name='mspec',
            name='is_floating',
            field=models.BooleanField(db_index=True, null=True, verbose_name='floating vs. in-place'),
        ),
    ]
