# Generated by Django 3.0.7 on 2020-06-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plotter", "0003_auto_20200620_2320"),
    ]

    operations = [
        migrations.RemoveField(model_name="spectrum", name="observation",),
        migrations.AddField(
            model_name="mspec",
            name="observation",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="spectra_set",
                to="plotter.MObs",
            ),
            preserve_default=False,
        ),
    ]
