# Generated by Django 3.2.3 on 2021-05-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mspec',
            name='ingest_time',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Ingest Time UTC'),
        ),
        migrations.AddField(
            model_name='zspec',
            name='ingest_time',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Ingest Time UTC'),
        ),
    ]
