# Generated by Django 3.1.7 on 2021-04-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mspec',
            name='filename',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Source CSV Filename'),
        ),
        migrations.AlterField(
            model_name='mspec',
            name='images',
            field=models.TextField(blank=True, db_index=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='mspec',
            name='seq_id',
            field=models.CharField(db_index=True, max_length=20, verbose_name='sequence id'),
        ),
        migrations.AlterField(
            model_name='zspec',
            name='filename',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Source CSV Filename'),
        ),
        migrations.AlterField(
            model_name='zspec',
            name='images',
            field=models.TextField(blank=True, db_index=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='zspec',
            name='seq_id',
            field=models.CharField(db_index=True, max_length=20, verbose_name='sequence id'),
        ),
    ]
