# Generated by Django 3.2.3 on 2021-05-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0002_auto_20210528_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zspec',
            name='roi_set_name',
        ),
        migrations.AddField(
            model_name='zspec',
            name='analysis_name',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='analysis / ROI set name'),
        ),
    ]
