# Generated by Django 3.1.7 on 2021-04-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0002_zobs_zspec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zobs',
            name='dcs_image',
        ),
        migrations.AddField(
            model_name='zobs',
            name='pointing_index',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Pointing Index'),
        ),
        migrations.AddField(
            model_name='zobs',
            name='rgb_image',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='path to rgb image'),
        ),
    ]
