# Generated by Django 3.1.7 on 2021-04-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0004_auto_20210404_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='zobs',
            name='zoom',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, verbose_name='Focal Length'),
        ),
    ]
