# Generated by Django 3.1.7 on 2021-04-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0005_zobs_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zspec',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spectra_set', to='plotter.zobs'),
        ),
    ]
