# Generated by Django 3.1.7 on 2021-04-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0006_auto_20210404_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mspec',
            name='feature_type',
        ),
        migrations.RemoveField(
            model_name='zspec',
            name='feature_type',
        ),
    ]
