import datetime as dt
import os
import re
from io import BytesIO
from pathlib import Path

import plotly.graph_objects as go
import wand.image

import plotter.application
from plotter.config.output_style import (
    BASE_SIZE_SETTING,
    GRAPH_SETTINGS,
    AXIS_SETTINGS,
    MARKER_SETTINGS,
    COLORBAR_SETTINGS,
    SCATTER_POINT_SCALE_SETTING,
)


def make_svg_font_style_block():
    asset_path = str(
        Path(Path(plotter.application.__file__).parent, "assets/")
    )
    font_path = Path(asset_path, "fonts")
    font_stylesheet_path = Path(asset_path, "css/fonts.css")
    with open(font_stylesheet_path) as font_stylesheet:
        fonts_css = font_stylesheet.read()
    fonts_css = fonts_css.replace("../fonts", str(font_path))
    return f"<style>{fonts_css}</style>"


def inject_style_into_svg(svgtext, style):
    """
    crudely inject a style block (or whatever) into the first <defs> block
    of an svg file expressed as a string
    """
    defs_end = re.search("defs.*?>", svgtext).span()[1]
    return svgtext[:defs_end] + style + svgtext[defs_end:]


def load_svg_as_wand(injected_svg):
    # have to do this weird hack to trick ImageMagick into finding the fonts...
    with open("temp_svg.svg", "w") as file:
        file.write(injected_svg)
    wand_image = wand.image.Image(filename="temp_svg.svg")
    os.unlink("temp_svg.svg")
    return wand_image


def inject_fonts_and_reload(svgtext):
    font_style_block = make_svg_font_style_block()
    svgtext = inject_style_into_svg(svgtext, font_style_block)
    return load_svg_as_wand(svgtext)


def apply_output_image_style(fig):
    fig.update_layout(**GRAPH_SETTINGS)
    fig.update_xaxes(**AXIS_SETTINGS)
    fig.update_yaxes(**AXIS_SETTINGS)
    for trace in fig.select_traces():
        marker = trace.marker
        if isinstance(marker.size, int):
            marker_size = marker.size * SCATTER_POINT_SCALE_SETTING
        else:
            marker_size = [
                SCATTER_POINT_SCALE_SETTING * size for size in marker.size
            ]
        trace.update(marker=MARKER_SETTINGS | {"size": marker_size})
    # again, hacky to use typesetting as layout, but...

    coloraxis = next(fig.select_coloraxes())
    if coloraxis:
        if "colorbar" in coloraxis:
            colorbar = coloraxis.colorbar
            if len(colorbar.title.text) > 12:
                colorbar.title.side = "right"
                colorbar.title.text = f"<br><br><br> &nbsp;{coloraxis.colorbar.title.text}"

            else:
                colorbar.title.side = "top"
                colorbar.title.text = f"{coloraxis.colorbar.title.text}<br> &nbsp;"
            colorbar.tickvals = coloraxis.colorbar.tickvals
            coloraxis["colorbar"] = colorbar
            fig.update_coloraxes(coloraxis)
    return fig


def save_main_scatter_plot(scatter_fig_dict, aspect_ratio):
    """
    main_scatter_fig: dict rep of figure generated by main_scatter_graph()
    aspect_ratio: its aspect ratio onscreen (w/h)
    """
    scatter_fig = go.Figure(scatter_fig_dict)
    scatter_fig = apply_output_image_style(scatter_fig)
    svgtext = scatter_fig.to_image(
        format="svg",
        width=BASE_SIZE_SETTING * aspect_ratio,
        height=BASE_SIZE_SETTING,
    ).decode()
    return inject_fonts_and_reload(svgtext).make_blob('png')
